// <auto-generated />
namespace GroceryStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class mig_two : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_two));
        
        string IMigrationMetadata.Id
        {
            get { return "201812201557198_mig_two"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
